/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chats
         * @description All chats, most recently active first.
         */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        /** Create Chat */
        post: operations["create_chat_api_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat
         * @description Stops running answers of the chat first.
         */
        delete: operations["delete_chat_api_chats__chat_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Chat
         * @description A new title is the user's and is never replaced automatically.
         */
        patch: operations["update_chat_api_chats__chat_id__patch"];
        trace?: never;
    };
    "/api/chats/{chat_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Attachments
         * @description Documents uploaded into this chat, newest first. Poll while any is processing.
         */
        get: operations["list_attachments_api_chats__chat_id__attachments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/attachments/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Attachment
         * @description Removes the document from this chat. One that is neither in the library nor in another
         *     chat is deleted completely (file, index, cited text).
         */
        delete: operations["remove_attachment_api_chats__chat_id__attachments__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description All messages, oldest first.
         */
        get: operations["list_messages_api_chats__chat_id__messages_get"];
        put?: never;
        /**
         * Ask
         * @description Asks a question and streams the answer. Without an API key the stream carries the
         *     sources only (`done.status = sources_only`).
         */
        post: operations["ask_api_chats__chat_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/messages/{assistant_id}/prefer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prefer
         * @description Keeps this answer of a comparison; only the kept answer goes into later history.
         */
        post: operations["prefer_api_chats__chat_id__messages__assistant_id__prefer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/messages/{assistant_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate
         * @description Replaces an answer to the latest question (same lane, same message id).
         */
        post: operations["regenerate_api_chats__chat_id__messages__assistant_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description Second safety net next to aborting the request: stops the lane's answer, which is then
         *     saved as `stopped`.
         */
        post: operations["stop_api_chats__chat_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description Loaded at start. The UI loads it again when an answer reveals a change: a rejected key
         *     (`llm_status`), a model Claude does not know (`available`), the budget.
         */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description The library, newest first. Poll while any is not `ready` or `failed`. Documents
         *     uploaded into a chat are listed by `GET /api/chats/{chat_id}/attachments`.
         */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Raw body, one file per request. Answers 202 at once; ingestion runs in the background.
         *     Without `chat_id` the file goes into the library; an attachment with the same bytes
         *     moves there instead of 409.
         */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/import-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Url
         * @description Downloads a PDF, HTML page, text or Markdown file from a link in the background and
         *     feeds it to the upload path (checks, malware scan, ingestion). Poll the job. Refused at
         *     once: URL_INVALID, URL_BLOCKED (local, private or internal addresses), RATE_LIMITED.
         *     Later, in the job: URL_UNREACHABLE, URL_TIMEOUT, URL_TOO_LARGE, URL_UNSUPPORTED_TYPE and
         *     the upload errors.
         */
        post: operations["import_url_api_documents_import_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Import
         * @description Progress (`received_bytes` of `total_bytes`), then the document or the error.
         */
        get: operations["get_import_api_documents_imports__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Import
         * @description Stops a running download; a document already handed over stays.
         */
        delete: operations["cancel_import_api_documents_imports__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Allowed in every status; stops a running ingestion.
         */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chunk
         * @description One chunk with its sentences and line rectangles, for highlighting a citation.
         */
        get: operations["get_chunk_api_documents__document_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document File
         * @description The original file with safe headers. Supports Range requests (PDF viewer).
         */
        get: operations["get_document_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Document To Library
         * @description Moves a chat attachment into the library. Idempotent.
         */
        post: operations["add_document_to_library_api_documents__document_id__library_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Text
         * @description TXT/MD/HTML as the decoded, normalized text that sentence offsets refer to (text
         *     viewer). For HTML that is the visible text of the page, without markup.
         */
        get: operations["get_document_text_api_documents__document_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description No dependencies. Electron uses `app` to verify it talks to this application.
         */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Ready means search works. A missing API key does not block readiness.
         */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preferences
         * @description The defaults (`onboarded` false) until the setup ran.
         */
        get: operations["get_preferences_api_preferences_get"];
        /**
         * Put Preferences
         * @description The whole object. 422 `MODEL_NOT_ALLOWED` for a model that is not offered.
         */
        put: operations["put_preferences_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Api Key
         * @description Whether a key is set, where it comes from and how it was checked. Never the key.
         */
        get: operations["get_api_key_api_settings_api_key_get"];
        /**
         * Put Api Key
         * @description Checks the key with a free call, then stores it on this machine and uses it from the
         *     next question on. 422 `API_KEY_INVALID` when Anthropic refuses it (nothing is stored).
         */
        put: operations["put_api_key_api_settings_api_key_put"];
        post?: never;
        /**
         * Delete Api Key
         * @description Forgets the key from Settings; ANTHROPIC_API_KEY applies again if it is set.
         */
        delete: operations["delete_api_key_api_settings_api_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_workspace_get"];
        put?: never;
        post?: never;
        /**
         * Delete Workspace
         * @description Deletes every document, chat and message. Running answers are stopped first.
         */
        delete: operations["delete_workspace_api_workspace_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Workspace
         * @description ZIP with every chat (JSON and Markdown), the preferences and the document list.
         */
        get: operations["export_workspace_api_workspace_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerStyle
         * @enum {string}
         */
        AnswerStyle: "concise" | "detailed";
        /** ApiKeyIn */
        ApiKeyIn: {
            /**
             * Key
             * @description Never returned, never logged.
             */
            key: string;
        };
        /**
         * ApiKeyOut
         * @description What the UI may know about the key: never the key, only its last four characters.
         */
        ApiKeyOut: {
            /** Configured */
            configured: boolean;
            /** @description settings wins over env (ANTHROPIC_API_KEY). */
            source: components["schemas"]["KeySource"] | null;
            status: components["schemas"]["LlmStatus"];
            /**
             * Suffix
             * @description The last four characters, for recognizing it.
             */
            suffix: string | null;
        };
        /** AskIn */
        AskIn: {
            /**
             * Client Message Id
             * Format: uuid
             * @description Created by the client; a repeat is ignored.
             */
            client_message_id: string;
            comparison?: components["schemas"]["ComparisonIn"] | null;
            /** Content */
            content: string;
            effort?: components["schemas"]["Effort"] | null;
            locale: components["schemas"]["Locale"];
            /** Model */
            model: string;
            /** @default concise */
            style: components["schemas"]["AnswerStyle"];
        };
        /**
         * BudgetOut
         * @description Only present with DAILY_BUDGET_USD. Resets at midnight UTC.
         */
        BudgetOut: {
            /** Exceeded */
            exceeded: boolean;
            /** Limit Usd */
            limit_usd: number;
            /**
             * Reset Time
             * Format: date-time
             */
            reset_time: string;
            /** Spent Usd */
            spent_usd: number;
        };
        /** ChatEnvelopeOut */
        ChatEnvelopeOut: {
            chat: components["schemas"]["ChatOut"];
        };
        /** ChatListItemOut */
        ChatListItemOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Ids */
            document_ids: string[];
            /** Id */
            id: string;
            /** Message Count */
            message_count: number;
            scope: components["schemas"]["ChatScope"];
            /**
             * Title
             * @description None: show the localized 'New chat'. Render as text.
             */
            title: string | null;
            title_source: components["schemas"]["TitleSource"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChatListOut */
        ChatListOut: {
            /** Chats */
            chats: components["schemas"]["ChatListItemOut"][];
        };
        /** ChatOut */
        ChatOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Ids */
            document_ids: string[];
            /** Id */
            id: string;
            scope: components["schemas"]["ChatScope"];
            /**
             * Title
             * @description None: show the localized 'New chat'. Render as text.
             */
            title: string | null;
            title_source: components["schemas"]["TitleSource"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChatScope
         * @description `all`: every `ready` document at question time. `selected`: the chosen ones.
         * @enum {string}
         */
        ChatScope: "all" | "selected";
        /** ChunkOut */
        ChunkOut: {
            /** Chunk Id */
            chunk_id: string;
            /** Page */
            page: number | null;
            /**
             * Precise Highlight
             * @description False: highlight the page, not the sentences.
             */
            precise_highlight: boolean;
            /** Sentences */
            sentences: components["schemas"]["SentenceOut"][];
            /** Text */
            text: string;
        };
        /** CitationOut */
        CitationOut: {
            /**
             * Block End
             * @description Exclusive.
             */
            block_end: number;
            /** Block Start */
            block_start: number;
            /**
             * Char Offset
             * @description Position in the answer text where the chip goes.
             */
            char_offset: number;
            /** Cited Text */
            cited_text: string;
            /** Source Id */
            source_id: string;
        };
        /** ComparisonIn */
        ComparisonIn: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lane: components["schemas"]["Lane"];
        };
        /**
         * ComponentStatus
         * @enum {string}
         */
        ComponentStatus: "loading" | "ok" | "failed";
        /** ConfigOut */
        ConfigOut: {
            budget: components["schemas"]["BudgetOut"] | null;
            /** Commit */
            commit: string;
            /** Default Model */
            default_model: string;
            features: components["schemas"]["Features"];
            limits: components["schemas"]["Limits"];
            llm_status: components["schemas"]["LlmStatus"];
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Version */
            version: string;
        };
        /** CreateChatIn */
        CreateChatIn: {
            /**
             * Document Ids
             * @description Only for `selected`.
             */
            document_ids?: string[];
            /** @default all */
            scope: components["schemas"]["ChatScope"];
        };
        /** DocumentEnvelopeOut */
        DocumentEnvelopeOut: {
            document: components["schemas"]["DocumentOut"];
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "pdf" | "txt" | "md" | "html";
        /** DocumentListOut */
        DocumentListOut: {
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /** Chunk Count */
            chunk_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @description Why the document is `failed`. */
            error_code: components["schemas"]["ErrorCode"] | null;
            /**
             * Error Params
             * @description Details for the error text, e.g. the signature for MALWARE_DETECTED.
             */
            error_params: {
                [key: string]: number | string;
            };
            /**
             * Filename
             * @description Display name only. Render as text, never as HTML.
             */
            filename: string;
            /** Id */
            id: string;
            /**
             * In Library
             * @description False: uploaded into a chat, listed and searched only there.
             */
            in_library: boolean;
            kind: components["schemas"]["DocumentKind"];
            /** Notices */
            notices: components["schemas"]["NoticeOut"][];
            /** Page Count */
            page_count: number | null;
            /**
             * Progress
             * @description 0..1 within the current status.
             */
            progress: number;
            /**
             * Queue Position
             * @description 1-based place in the queue while queued.
             */
            queue_position: number | null;
            /** Ready At */
            ready_at: string | null;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Source Url
             * @description The link it was imported from. Render as text.
             */
            source_url?: string | null;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * DocumentStatus
         * @description `scanning` belongs to the malware check (WP-B). `deleting` hides a row until it is gone.
         * @enum {string}
         */
        DocumentStatus: "scanning" | "queued" | "parsing" | "embedding" | "ready" | "failed" | "deleting";
        /**
         * Effort
         * @enum {string}
         */
        Effort: "low" | "medium" | "high";
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Details */
            details?: {
                [key: string]: unknown;
            }[];
            /**
             * Message
             * @description Developer-facing text for logs. The UI translates `code`.
             */
            message: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string;
            /**
             * Retry After
             * @default null
             */
            retry_after: number | null;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "UNAUTHORIZED_CLIENT" | "SERVICE_STARTING" | "INTERNAL_ERROR" | "REQUEST_TOO_LARGE" | "RATE_LIMITED" | "UPLOAD_TOO_LARGE" | "UNSUPPORTED_TYPE" | "FILE_CONTENT_MISMATCH" | "EMPTY_FILE" | "DUPLICATE_DOCUMENT" | "STORAGE_QUOTA" | "STORAGE_FULL" | "UPLOAD_INCOMPLETE" | "URL_INVALID" | "URL_BLOCKED" | "URL_UNREACHABLE" | "URL_TIMEOUT" | "URL_TOO_LARGE" | "URL_UNSUPPORTED_TYPE" | "DOCUMENT_NOT_READY" | "DOCUMENT_FILE_MISSING" | "DELETE_FAILED" | "RANGE_NOT_SATISFIABLE" | "PDF_ENCRYPTED" | "PDF_CORRUPT" | "PDF_NO_TEXT" | "PDF_TOO_MANY_PAGES" | "TEXT_ENCODING_UNSUPPORTED" | "DOCUMENT_EMPTY" | "DOCUMENT_TOO_LONG" | "PROCESSING_TIMEOUT" | "PROCESSING_FAILED" | "PROCESSING_INTERRUPTED" | "MALWARE_DETECTED" | "MALWARE_SCAN_FAILED" | "CHAT_NOT_FOUND" | "CHAT_BUSY" | "CHAT_LIMIT" | "MESSAGE_LIMIT" | "MESSAGE_NOT_LATEST" | "DUPLICATE_REQUEST" | "CONCURRENCY_LIMIT" | "NO_DOCUMENTS" | "DOCUMENTS_NOT_READY" | "QUESTION_EMPTY" | "QUESTION_TOO_LONG" | "MODEL_NOT_ALLOWED" | "COMPARE_SAME_MODEL" | "TOKEN_BUDGET_EXCEEDED" | "LLM_AUTH" | "API_KEY_INVALID" | "LLM_BILLING" | "LLM_FORBIDDEN" | "MODEL_UNAVAILABLE" | "LLM_RATE_LIMITED" | "LLM_OVERLOADED" | "LLM_UNAVAILABLE" | "LLM_TIMEOUT" | "LLM_UNREACHABLE" | "LLM_BAD_REQUEST" | "LLM_CONTEXT_TOO_LARGE" | "LLM_EMPTY_ANSWER";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ErrorStage
         * @enum {string}
         */
        ErrorStage: "retrieval" | "llm" | "persist";
        /** Features */
        Features: {
            /** Retrieval Only */
            retrieval_only: boolean;
        };
        /** ImportEnvelopeOut */
        ImportEnvelopeOut: {
            job: components["schemas"]["ImportOut"];
        };
        /** ImportOut */
        ImportOut: {
            /** @description Once `done`: the new document. */
            document: components["schemas"]["DocumentOut"] | null;
            /** @description Why the import `failed`. */
            error_code: components["schemas"]["ErrorCode"] | null;
            /** Error Params */
            error_params: {
                [key: string]: number | string;
            };
            /** Id */
            id: string;
            /** Received Bytes */
            received_bytes: number;
            state: components["schemas"]["ImportState"];
            /**
             * Total Bytes
             * @description From Content-Length; null when unknown.
             */
            total_bytes: number | null;
            /**
             * Url
             * @description The normalized link. Render as text.
             */
            url: string;
        };
        /**
         * ImportState
         * @enum {string}
         */
        ImportState: "downloading" | "done" | "failed";
        /** ImportUrlIn */
        ImportUrlIn: {
            /**
             * Chat Id
             * @description Import into this chat.
             */
            chat_id?: string | null;
            /**
             * Library
             * @description Also into the library. Without `chat_id` always true.
             * @default true
             */
            library: boolean;
            /**
             * Url
             * @description http or https; no credentials.
             */
            url: string;
        };
        /**
         * KeySource
         * @enum {string}
         */
        KeySource: "settings" | "env";
        /**
         * Lane
         * @description Single answers always use `a`; the comparison mode adds `b`.
         * @enum {string}
         */
        Lane: "a" | "b";
        /** LatencyOut */
        LatencyOut: {
            /** Total */
            total: number | null;
            /**
             * Ttft
             * @description Milliseconds until the first text.
             */
            ttft: number | null;
        };
        /**
         * Limits
         * @description Known to the UI so it can reject files and questions before sending them.
         */
        Limits: {
            /**
             * Chat Per Minute
             * @description Own limit for questions; 0 is off.
             */
            chat_per_minute: number;
            /**
             * Daily Budget Usd
             * @description Optional cost brake; null is off.
             */
            daily_budget_usd: number | null;
            /** Max Concurrent Answers */
            max_concurrent_answers: number;
            /** Max Pdf Pages */
            max_pdf_pages: number;
            /** Max Question Chars */
            max_question_chars: number;
            /** Max Storage Mb */
            max_storage_mb: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /**
             * Uploads Per Minute
             * @description Own limit for uploads; 0 is off.
             */
            uploads_per_minute: number;
        };
        /** LiveOut */
        LiveOut: {
            /** App */
            app: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * LlmStatus
         * @enum {string}
         */
        LlmStatus: "missing_key" | "unchecked" | "ok" | "invalid_key";
        /**
         * Locale
         * @enum {string}
         */
        Locale: "de" | "en";
        /** MessageListOut */
        MessageListOut: {
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /** MessageOut */
        MessageOut: {
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Client Message Id */
            client_message_id: string | null;
            /** Comparison Id */
            comparison_id: string | null;
            /**
             * Content
             * @description Markdown without citation markers.
             */
            content: string;
            /** Cost Usd */
            cost_usd: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            effort: components["schemas"]["Effort"] | null;
            error_code: components["schemas"]["ErrorCode"] | null;
            /**
             * Error Request Id
             * @description Request of a failed answer, for the logs.
             */
            error_request_id: string | null;
            /** Id */
            id: string;
            /** Is Preferred */
            is_preferred: boolean;
            lane: components["schemas"]["Lane"] | null;
            latency_ms: components["schemas"]["LatencyOut"];
            /**
             * Model
             * @description The model that actually answered.
             */
            model: string | null;
            /** Notices */
            notices: components["schemas"]["NoticeOut"][];
            /** Parent Id */
            parent_id: string | null;
            role: components["schemas"]["MessageRole"];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            sources_mode: components["schemas"]["SourcesMode"] | null;
            status: components["schemas"]["MessageStatus"];
            usage: components["schemas"]["UsageOut"] | null;
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * MessageStatus
         * @description Only `complete` and `truncated` answers go into the history sent to the model.
         * @enum {string}
         */
        MessageStatus: "streaming" | "complete" | "truncated" | "stopped" | "interrupted" | "refused" | "error" | "sources_only";
        /** ModelInfo */
        ModelInfo: {
            /** Available */
            available: boolean;
            /** Cache Read Usd Per Mtok */
            cache_read_usd_per_mtok: number;
            default_effort: components["schemas"]["Effort"] | null;
            /** Efforts */
            efforts: components["schemas"]["Effort"][];
            /** Id */
            id: string;
            /** Input Usd Per Mtok */
            input_usd_per_mtok: number;
            /** Label */
            label: string;
            /** Output Usd Per Mtok */
            output_usd_per_mtok: number;
            /** Tier */
            tier: string;
        };
        /**
         * NoticeCode
         * @description Hints that are not errors. The UI translates them via `notices.<CODE>`.
         * @enum {string}
         */
        NoticeCode: "PAGES_WITHOUT_TEXT" | "PAGES_OCR" | "OCR_RUNNING" | "PAGES_SKIPPED" | "PDF_ACTIVE_CONTENT" | "SCANNER_STARTING" | "SCANNER_UNAVAILABLE" | "SOURCES_PARTIAL" | "SUMMARY_PARTIAL" | "NO_CITATIONS" | "ANSWER_TRUNCATED" | "LLM_REFUSED" | "LLM_NOT_CONFIGURED" | "MODEL_SWITCHED" | "HIGHLIGHT_UNAVAILABLE";
        /** NoticeOut */
        NoticeOut: {
            code: components["schemas"]["NoticeCode"];
            /** Params */
            params?: {
                [key: string]: number | string;
            };
        };
        /**
         * PreferencesBody
         * @description Always the whole object (annex 11, 3.2).
         */
        PreferencesBody: {
            /** Compare Models */
            compare_models: string[];
            /** Default Model */
            default_model: string;
            /** @description Answer mode: fast (low), balanced, thorough (high). */
            effort: components["schemas"]["Effort"];
            locale: components["schemas"]["Locale"];
            /**
             * Name
             * @description Only for the greeting, never sent to the model. Cleaned on save.
             */
            name: string;
            /** Onboarded */
            onboarded: boolean;
            /**
             * Retention Days
             * @description Delete chats and documents after this many days; 0 is off. Until chosen, the installation default (RETENTION_DAYS). Omitted on PUT: stays as it is (clients written before this field existed).
             */
            retention_days?: number | null;
            style: components["schemas"]["AnswerStyle"];
            theme: components["schemas"]["Theme"];
        };
        /** ReadyChecks */
        ReadyChecks: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "failed";
            embedding_model: components["schemas"]["ComponentStatus"];
            llm: components["schemas"]["LlmStatus"];
            vector_store: components["schemas"]["ComponentStatus"];
        };
        /** ReadyOut */
        ReadyOut: {
            checks: components["schemas"]["ReadyChecks"];
            /** Ready */
            ready: boolean;
        };
        /** RegenerateIn */
        RegenerateIn: {
            effort?: components["schemas"]["Effort"] | null;
            locale: components["schemas"]["Locale"];
            /**
             * Model
             * @description Default: the answer's model.
             */
            model?: string | null;
            /** @default concise */
            style: components["schemas"]["AnswerStyle"];
        };
        /**
         * RunPhase
         * @enum {string}
         */
        RunPhase: "retrieving" | "generating" | "retrying";
        /** SentenceOut */
        SentenceOut: {
            /** Char End */
            char_end: number;
            /**
             * Char Start
             * @description Offset in the page text (PDF) or document text (TXT/MD).
             */
            char_start: number;
            /** I */
            i: number;
            /**
             * Rects
             * @description One (x, y, w, h) per line, 0..1 of the displayed page, origin top left.
             */
            rects: [
                number,
                number,
                number,
                number
            ][];
            /** Text */
            text: string;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Deleted
             * @description The document is gone; show the snapshot, open nothing.
             */
            deleted: boolean;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * @description Chunk id; citations refer to it as `source_id`.
             */
            id: string;
            /**
             * Index
             * @description 1-based number of the source chip.
             */
            index: number;
            /** Page */
            page: number | null;
            /** Snippet */
            snippet: string;
        };
        /**
         * SourcesMode
         * @description How the sources of an answer were chosen.
         * @enum {string}
         */
        SourcesMode: "retrieval" | "full_context" | "retrieval_only";
        /**
         * SseCitation
         * @description `event: citation`: sent when its text block ends; `char_offset` is final.
         */
        SseCitation: {
            /**
             * Block End
             * @description Exclusive.
             */
            block_end: number;
            /** Block Start */
            block_start: number;
            /**
             * Char Offset
             * @description Position in the answer text where the chip goes.
             */
            char_offset: number;
            /** Cited Text */
            cited_text: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * SseDelta
         * @description `event: delta`: the next piece of answer text.
         */
        SseDelta: {
            /** Text */
            text: string;
        };
        /**
         * SseDone
         * @description `event: done`: the terminal event of a finished, stopped or sources-only answer.
         */
        SseDone: {
            chat: components["schemas"]["SseDoneChat"];
            /** Cost Usd */
            cost_usd: number;
            latency_ms: components["schemas"]["LatencyOut"];
            /** Notices */
            notices: components["schemas"]["NoticeOut"][];
            status: components["schemas"]["MessageStatus"];
            /** Stop Reason */
            stop_reason: string | null;
            usage: components["schemas"]["UsageOut"] | null;
        };
        /** SseDoneChat */
        SseDoneChat: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SseError
         * @description `event: error`: the terminal event of a failed answer.
         */
        SseError: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Partial
             * @description Text was streamed and stays visible as incomplete.
             */
            partial: boolean;
            stage: components["schemas"]["ErrorStage"];
        };
        /**
         * SseMeta
         * @description `event: meta`, always first.
         */
        SseMeta: {
            /** Assistant Message Id */
            assistant_message_id: string;
            /** Chat Id */
            chat_id: string;
            /** Comparison Id */
            comparison_id: string | null;
            lane: components["schemas"]["Lane"];
            /**
             * Model
             * @description The requested model; a switch shows as MODEL_SWITCHED.
             */
            model: string;
            /** Request Id */
            request_id: string;
            /** User Message Id */
            user_message_id: string;
        };
        /**
         * SseSources
         * @description `event: sources`: what the answer is based on, numbered for the chips.
         */
        SseSources: {
            mode: components["schemas"]["SourcesMode"];
            /** Notices */
            notices: components["schemas"]["NoticeOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /**
         * SseStatus
         * @description `event: status`: retrieving, generating, retrying (before the first delta only).
         */
        SseStatus: {
            /** Attempt */
            attempt: number;
            phase: components["schemas"]["RunPhase"];
        };
        /** StopIn */
        StopIn: {
            /** @description Without a lane every lane stops. */
            lane?: components["schemas"]["Lane"] | null;
        };
        /** StopOut */
        StopOut: {
            /** Stopped */
            stopped: components["schemas"]["Lane"][];
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "light" | "dark" | "system";
        /**
         * TitleSource
         * @enum {string}
         */
        TitleSource: "auto" | "user";
        /** UpdateChatIn */
        UpdateChatIn: {
            /** Document Ids */
            document_ids?: string[] | null;
            scope?: components["schemas"]["ChatScope"] | null;
            /**
             * Title
             * @description 1 to 120 characters.
             */
            title?: string | null;
        };
        /** UsageMonthOut */
        UsageMonthOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Requests */
            requests: number;
        };
        /** UsageOut */
        UsageOut: {
            /** Cache Creation Input Tokens */
            cache_creation_input_tokens: number;
            /** Cache Read Input Tokens */
            cache_read_input_tokens: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** UsageTodayOut */
        UsageTodayOut: {
            /**
             * Budget Usd
             * @description DAILY_BUDGET_USD; null is off.
             */
            budget_usd: number | null;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Requests */
            requests: number;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Retention Days
             * @description From the preferences; null: nothing is deleted automatically.
             */
            retention_days: number | null;
            stats: components["schemas"]["WorkspaceStatsOut"];
            /** @description Since the first of the current UTC month: what this app spent at Anthropic. */
            usage_month: components["schemas"]["UsageMonthOut"];
            /** @description The current UTC day. */
            usage_today: components["schemas"]["UsageTodayOut"];
        };
        /** WorkspaceStatsOut */
        WorkspaceStatsOut: {
            /** Chats */
            chats: number;
            /** Documents */
            documents: number;
            /**
             * Documents Bytes
             * @description Size of the original files.
             */
            documents_bytes: number;
            /**
             * Storage Bytes
             * @description Everything on disk: files, search index, database.
             */
            storage_bytes: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chats_api_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListOut"];
                };
            };
        };
    };
    create_chat_api_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_chat_api_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_chat_api_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_attachments_api_chats__chat_id__attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    remove_attachment_api_chats__chat_id__attachments__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_messages_api_chats__chat_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ask_api_chats__chat_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Events `meta`, `status`, `sources`, `delta`, `citation`, then exactly one `done` or `error` (payloads: Sse* schemas). A `: ping` comment every 15 s. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Refused before the stream opened. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    prefer_api_chats__chat_id__messages__assistant_id__prefer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
                assistant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    regenerate_api_chats__chat_id__messages__assistant_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
                assistant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateIn"];
            };
        };
        responses: {
            /** @description Events `meta`, `status`, `sources`, `delta`, `citation`, then exactly one `done` or `error` (payloads: Sse* schemas). A `: ping` comment every 15 s. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Refused before the stream opened. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the stream opened. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stop_api_chats__chat_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StopIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: {
                /** @description Upload into this chat: searched only there, not listed in the library. The same file again attaches the existing document instead of 409. */
                chat_id?: string | null;
            };
            header: {
                /** @description Percent-encoded UTF-8 file name. */
                "x-file-name": string;
                "content-length"?: number | null;
                "content-type"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEnvelopeOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    import_url_api_documents_import_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_import_api_documents_imports__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancel_import_api_documents_imports__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_chunk_api_documents__document_id__chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_document_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Partial content for a Range request. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested Range Not Satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    add_document_to_library_api_documents__document_id__library_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_document_text_api_documents__document_id__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesBody"];
                };
            };
        };
    };
    put_preferences_api_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_api_key_api_settings_api_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
        };
    };
    put_api_key_api_settings_api_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_api_key_api_settings_api_key_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
        };
    };
    get_workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
        };
    };
    delete_workspace_api_workspace_delete: {
        parameters: {
            query?: {
                /** @description Also forget name and settings; the setup shows again. */
                reset_preferences?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_workspace_api_workspace_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
}
